from __future__ import annotations

import hashlib
import subprocess
from pathlib import Path

import pytest
from tools.cleanai_core.model import ConfigurationError
from tools.cleanai_core.science import science_findings


def _repo(root: Path) -> Path:
    for relative in (
        "CONTRIBUTING.md",
        "SECURITY.md",
        ".github/pull_request_template.md",
        ".env.example",
        ".envrc",
        "notebooks/README.md",
        "results/README.md",
        "results/.gitignore",
        "results/reference/README.md",
        "scripts/README.md",
        "static/README.md",
    ):
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("fixture\n", encoding="utf-8")
    (root / ".gitignore").write_text(
        ".env\n.env.*\n!.env.example\n.direnv/\n.ipynb_checkpoints/\n",
        encoding="utf-8",
    )
    (root / "results/.gitignore").write_text(
        "*\n!.gitignore\n!README.md\n!reference/\n!reference/**\n",
        encoding="utf-8",
    )
    (root / "static/manifest.toml").write_text("schema_version = 1\nfiles = []\n", encoding="utf-8")
    (root / ".cleanai").mkdir()
    (root / ".cleanai/policy.toml").write_text(
        '[project]\nsource_root = "src/pkg"\n', encoding="utf-8"
    )
    source = root / "src/pkg"
    source.mkdir(parents=True)
    (source / "__init__.py").write_text("", encoding="utf-8")
    return root


def _codes(root: Path) -> set[str]:
    return {finding.code for finding in science_findings(root)}


def test_empty_scientific_profile_is_valid(tmp_path: Path) -> None:
    assert science_findings(_repo(tmp_path)) == []


def test_unregistered_static_input_fails(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    (root / "static/sample.csv").write_text("value\n1\n", encoding="utf-8")
    assert "science.static-unregistered" in _codes(root)


def test_registered_static_input_checks_hash_and_metadata(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    asset = root / "static/sample.csv"
    asset.write_text("value\n1\n", encoding="utf-8")
    digest = hashlib.sha256(asset.read_bytes()).hexdigest()
    manifest = (
        "schema_version = 1\n"
        "[[files]]\n"
        'path = "static/sample.csv"\n'
        f'sha256 = "{digest}"\n'
        'source = "generated by tests"\n'
        'license = "CC0-1.0"\n'
        'description = "one synthetic value"\n'
    )
    (root / "static/manifest.toml").write_text(manifest, encoding="utf-8")
    assert science_findings(root) == []
    (root / "static/sample.csv").write_text("value\n2\n", encoding="utf-8")
    assert "science.static-hash" in _codes(root)


@pytest.mark.parametrize(
    "path",
    ["../outside.csv", "/tmp/outside.csv", "static/../outside.csv", "other/file.csv"],
)
def test_manifest_rejects_paths_outside_static(tmp_path: Path, path: str) -> None:
    root = _repo(tmp_path)
    (root / "static/manifest.toml").write_text(
        "schema_version = 1\n"
        "[[files]]\n"
        f'path = "{path}"\n'
        f'sha256 = "{"0" * 64}"\n'
        'source = "fixture"\nlicense = "CC0-1.0"\ndescription = "fixture"\n',
        encoding="utf-8",
    )
    with pytest.raises(ConfigurationError, match="contained path below static"):
        science_findings(root)


def test_static_symlink_is_rejected(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    outside = root / "outside.csv"
    outside.write_text("private\n", encoding="utf-8")
    (root / "static/link.csv").symlink_to(outside)
    assert "science.static-symlink" in _codes(root)


def test_tracked_dotenv_is_detected_without_reading_value(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    subprocess.run(["git", "init", "-q"], cwd=root, check=True)
    (root / ".env.local").write_text("DO_NOT_EXPOSE=secret\n", encoding="utf-8")
    subprocess.run(["git", "add", "-f", ".env.local"], cwd=root, check=True)
    assert "science.tracked-secret" in _codes(root)


def test_missing_ignore_rule_fails_closed(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    (root / ".gitignore").write_text(".env\n", encoding="utf-8")
    assert "science.secret-ignore" in _codes(root)


def test_results_must_remain_ignored_by_default(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    (root / "results/.gitignore").write_text("!README.md\n", encoding="utf-8")
    assert "science.results-ignore" in _codes(root)


def test_product_cannot_import_workspace_directories(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    (root / "src/pkg/bad.py").write_text(
        "import notebooks.demo\nfrom static import sample\n", encoding="utf-8"
    )
    findings = science_findings(root)
    assert [item.code for item in findings].count("science.workspace-import") == 2
